name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Run installer for public GitHub repo
        run: ./release-installer zachcheung/release-installer
      - name: Run installer for public GitLab repo
        run: ./release-installer -provider gitlab goreleaser/example
