name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: false
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Run installer for public GitHub repo (package in the root directory)
        run: ./release-installer zachcheung/release-installer
      - name: Run installer for public GitHub repo (package in the subdirectory)
        run: ./release-installer prometheus/node_exporter
      - name: Run installer for public GitLab repo
        run: ./release-installer -provider gitlab goreleaser/example
      - name: Run installer for public GitHub repo with tag
        run: ./release-installer -tag v0.5.0 zachcheung/release-installer
      - name: Run installer for public GitHub repo with tag (no v prefix)
        run: ./release-installer -tag 0.5.0 zachcheung/release-installer
      - name: Run installer for public GitHub with pattern
        run: ./release-installer -tag v0.5.0 -pattern 'darwin_amd64' zachcheung/release-installer
